libemu: Update keyword argument name
I'd missed a keyword name refactor, causing prune to stack trace when
setting a new HEAD:

$ emu prune origin:HEAD
origin: removing snapshot 2014-09-11 22.09.51
origin: HEAD at 54121dae9f2b744570e8240ca43a483956f27056
Traceback (most recent call last):
  File "/usr/local/bin/emu-prune", line 53, in <module>
    ret = main(argv, len(argv))
  File "/usr/local/bin/emu-prune", line 46, in main
    snapshot.destroy(verbose=options.verbose)
  File "/usr/local/libexec/emu/libemu.py", line 765, in destroy
    snapshot.parent(parent=new_parent)
TypeError: parent() got an unexpected keyword argument 'parent'